modifying pipe

diff --git a/smoke-test-pipeline.yml b/smoke-test-pipeline.yml
--- a/smoke-test-pipeline.yml
+++ b/smoke-test-pipeline.yml
@@ -37,10 +37,10 @@ stages:
       failOnStderr: true
     - bash: |
         echo "FUNC_SCRIPT: $FUNC_SCRIPT"
-        curl --fail $FUNC_SCRIPT >| functions.sh
+        curl --fail $FUNC_SCRIPT >| functions.sh || {echo "Download Failed"; exit 1}
         chmod +x ./functions.sh
         echo "TEST_SCRIPT: $TEST_SCRIPT"
-        curl --fail $TEST_SCRIPT >| validations.sh
+        curl --fail $TEST_SCRIPT >| validations.sh || {echo "Download Failed"; exit 1}
         chmod +x ./validations.sh
       displayName: "Download integration test scripts"
       env:
@@ -105,10 +105,10 @@ stages:
       failOnStderr: true
     - bash: |
         echo "FUNC_SCRIPT: $FUNC_SCRIPT"
-        curl $FUNC_SCRIPT >| functions.sh
+        curl $FUNC_SCRIPT >| functions.sh || {echo "Download Failed"; exit 1}
         chmod +x ./functions.sh
         echo "TEST_SCRIPT2: $TEST_SCRIPT2"
-        curl $TEST_SCRIPT2 >| infra-validations.sh
+        curl $TEST_SCRIPT2 >| infra-validations.sh || {echo "Download Failed"; exit 1}
         chmod +x ./infra-validations.sh
       displayName: "Download integration test scripts"
       env:
