Testing pipeline wth infra validations

diff --git a/smoke-test-pipeline.yml b/smoke-test-pipeline.yml
--- a/smoke-test-pipeline.yml
+++ b/smoke-test-pipeline.yml
@@ -41,10 +41,14 @@ stages:
         echo "TEST_SCRIPT: $TEST_SCRIPT"
         curl $TEST_SCRIPT >| validations.sh
         chmod +x ./validations.sh
+        echo "TEST_SCRIPT2: $TEST_SCRIPT2"
+        curl $TEST_SCRIPT2 >| infra-validations.sh
+        chmod +x ./infra-validations.sh
       displayName: "Download integration test scripts"
       env:
         FUNC_SCRIPT: $(FUNC_SCRIPT)
         TEST_SCRIPT: $(TEST_SCRIPT)
+        TEST_SCRIPT2: $(TEST_SCRIPT2)
     - bash: | 
         # Install the extension
         export AZURE_DEVOPS_EXT_PAT=$(AZDO_PAT)
@@ -73,6 +77,14 @@ stages:
         # Get exit status
         status=$?
         [ $status -eq 0 ] && echo "Test Done!" || (echo "Test had issues" && exit 1)
+
+
+        # Run the test
+        bash ./infra-validations.sh
+
+        # Get exit status
+        status=$?
+        [ $status -eq 0 ] && echo "Infra Test Done!" || (echo "Infra Test had issues" && exit 1)
       #failOnStderr: true
       displayName: "Run Tests"
     - task: PublishPipelineArtifact@1
